theme: jekyll-theme-minimal
title: <p style="border:5px solid#4eb174;"</p><p style="color:#4eb174;">Qiaowoâ„¢ï¸'s Sus Page</p>
description: <h1 style="font-size:17px;"><p style="color:#4eb174;">ğŸ’š~Welcome to Qiaowoâ„¢ï¸'s GitHub~ğŸ’š</p></h1>
logo: /images/jam fluffly black cape (2).png
show_downloads: true
google_analytics: [UA-175791564-1]
