theme: jekyll-theme-minimal
title: <h1 style="border:2px solid DarkSeaGreen;">Qiaowo's Sus Page</h1>
description: [ðŸ’š~Welcome to Qiaowo's GitHub~ðŸ’š]<p style="color:MediumSeaGreen;">[ðŸ’š~Welcome to Qiaowo's GitHub~ðŸ’š]</p>
logo: /images/jam fluffly black cape (2).png
show_downloads: true
google_analytics: [UA-175791564-1]