theme: jekyll-theme-minimal
title: <p style="border:4px solid#4eb174;"</p><p style="color:#4eb174;">Qiaowo's Sus Page</p>
description: <p style="color:#4eb174;"><b>ðŸ’š~Welcome to Qiaowo's GitHub~ðŸ’š</b></p>
logo: /images/jam fluffly black cape (2).png
show_downloads: true
google_analytics: [UA-175791564-1]
